// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Payment struct {
	ID             int64
	Amount         int64
	Currency       string
	Reference      string
	Status         string
	CreatedAt      string
	IdempotencyKey sql.NullString
}
