// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Outbox struct {
	ID         int64
	Topic      string
	Payload    []byte
	CreatedAt  string
	SentAt     sql.NullString
	ErrorCount int64
}

type Payment struct {
	ID                  int64
	Amount              int64
	Currency            string
	Reference           string
	Status              string
	CreatedAt           string
	IdempotencyKey      sql.NullString
	NextRetryAt         sql.NullString
	Attempts            int64
	ProcessingStartedAt sql.NullString
}
