// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  amount, currency, reference, status, idempotency_key
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, amount, currency, reference, idempotency_key, status, created_at
`

type CreatePaymentParams struct {
	Amount         int64
	Currency       string
	Reference      string
	Status         string
	IdempotencyKey sql.NullString
}

type CreatePaymentRow struct {
	ID             int64
	Amount         int64
	Currency       string
	Reference      string
	IdempotencyKey sql.NullString
	Status         string
	CreatedAt      string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.Amount,
		arg.Currency,
		arg.Reference,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFailedPaymentsForRetry = `-- name: GetFailedPaymentsForRetry :many
SELECT idempotency_key, reference
FROM payments
WHERE status = 'failed'
  AND next_retry_at IS NOT NULL
  AND next_retry_at <= datetime('now')
  AND attempts < 5
LIMIT 50
`

type GetFailedPaymentsForRetryRow struct {
	IdempotencyKey sql.NullString
	Reference      string
}

func (q *Queries) GetFailedPaymentsForRetry(ctx context.Context) ([]GetFailedPaymentsForRetryRow, error) {
	rows, err := q.db.QueryContext(ctx, getFailedPaymentsForRetry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFailedPaymentsForRetryRow
	for rows.Next() {
		var i GetFailedPaymentsForRetryRow
		if err := rows.Scan(&i.IdempotencyKey, &i.Reference); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByIdempotency = `-- name: GetPaymentByIdempotency :one
SELECT
    amount,
    currency,
    idempotency_key,
    reference,
    status,
    attempts,
    next_retry_at,
    processing_started_at,
    created_at
FROM payments
WHERE idempotency_key = ? LIMIT 1
`

type GetPaymentByIdempotencyRow struct {
	Amount              int64
	Currency            string
	IdempotencyKey      sql.NullString
	Reference           string
	Status              string
	Attempts            int64
	NextRetryAt         sql.NullString
	ProcessingStartedAt sql.NullString
	CreatedAt           string
}

func (q *Queries) GetPaymentByIdempotency(ctx context.Context, idempotencyKey sql.NullString) (GetPaymentByIdempotencyRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByIdempotency, idempotencyKey)
	var i GetPaymentByIdempotencyRow
	err := row.Scan(
		&i.Amount,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT
    id,
    amount,
    currency,
    idempotency_key,
    reference,
    status,
    attempts,
    next_retry_at,
    processing_started_at,
    created_at
FROM payments
WHERE reference = ? LIMIT 1
`

type GetPaymentByReferenceRow struct {
	ID                  int64
	Amount              int64
	Currency            string
	IdempotencyKey      sql.NullString
	Reference           string
	Status              string
	Attempts            int64
	NextRetryAt         sql.NullString
	ProcessingStartedAt sql.NullString
	CreatedAt           string
}

func (q *Queries) GetPaymentByReference(ctx context.Context, reference string) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByReference, reference)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.ProcessingStartedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUnsentOutboxMessages = `-- name: GetUnsentOutboxMessages :many
SELECT id, topic, payload
FROM outbox
WHERE sent_at IS NULL
  AND error_count < 5
ORDER BY created_at ASC
LIMIT 50
`

type GetUnsentOutboxMessagesRow struct {
	ID      int64
	Topic   string
	Payload []byte
}

func (q *Queries) GetUnsentOutboxMessages(ctx context.Context) ([]GetUnsentOutboxMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getUnsentOutboxMessages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUnsentOutboxMessagesRow
	for rows.Next() {
		var i GetUnsentOutboxMessagesRow
		if err := rows.Scan(&i.ID, &i.Topic, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementOutboxErrorCount = `-- name: IncrementOutboxErrorCount :exec
UPDATE outbox
SET error_count = error_count + 1
WHERE id = ?
`

func (q *Queries) IncrementOutboxErrorCount(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, incrementOutboxErrorCount, id)
	return err
}

const insertOutbox = `-- name: InsertOutbox :exec
INSERT INTO outbox (topic, payload)
VALUES (?, ?)
`

type InsertOutboxParams struct {
	Topic   string
	Payload []byte
}

func (q *Queries) InsertOutbox(ctx context.Context, arg InsertOutboxParams) error {
	_, err := q.db.ExecContext(ctx, insertOutbox, arg.Topic, arg.Payload)
	return err
}

const markOutboxMessageSent = `-- name: MarkOutboxMessageSent :exec
UPDATE outbox
SET sent_at = datetime('now')
WHERE id = ?
`

func (q *Queries) MarkOutboxMessageSent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markOutboxMessageSent, id)
	return err
}

const resetStaleProcessingPayments = `-- name: ResetStaleProcessingPayments :execrows
UPDATE payments
SET status = 'failed',
    next_retry_at = datetime('now', '+1 minute')
WHERE status = 'processing'
  AND processing_started_at IS NOT NULL
  AND datetime(processing_started_at) <= datetime('now', '-2 minutes')
`

func (q *Queries) ResetStaleProcessingPayments(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, resetStaleProcessingPayments)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = ?,
    attempts = ?,
    next_retry_at = ?,
    processing_started_at = ?
WHERE idempotency_key = ?
`

type UpdatePaymentStatusParams struct {
	Status              string
	Attempts            int64
	NextRetryAt         sql.NullString
	ProcessingStartedAt sql.NullString
	IdempotencyKey      sql.NullString
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus,
		arg.Status,
		arg.Attempts,
		arg.NextRetryAt,
		arg.ProcessingStartedAt,
		arg.IdempotencyKey,
	)
	return err
}
