// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  amount, currency, reference, status
) VALUES (
  ?, ?, ?, ?
)
RETURNING amount, currency, reference, status, created_at
`

type CreatePaymentParams struct {
	Amount    int64
	Currency  string
	Reference string
	Status    string
}

type CreatePaymentRow struct {
	Amount    int64
	Currency  string
	Reference string
	Status    string
	CreatedAt string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.Amount,
		arg.Currency,
		arg.Reference,
		arg.Status,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT
    amount,
    currency,
    reference,
    status,
    created_at
FROM payments
WHERE reference = ? LIMIT 1
`

type GetPaymentByReferenceRow struct {
	Amount    int64
	Currency  string
	Reference string
	Status    string
	CreatedAt string
}

func (q *Queries) GetPaymentByReference(ctx context.Context, reference string) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByReference, reference)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
