// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  amount, currency, reference, status, idempotency_key
) VALUES (
  ?, ?, ?, ?, ?
)
RETURNING id, amount, currency, reference, idempotency_key, status, created_at
`

type CreatePaymentParams struct {
	Amount         int64
	Currency       string
	Reference      string
	Status         string
	IdempotencyKey sql.NullString
}

type CreatePaymentRow struct {
	ID             int64
	Amount         int64
	Currency       string
	Reference      string
	IdempotencyKey sql.NullString
	Status         string
	CreatedAt      string
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.Amount,
		arg.Currency,
		arg.Reference,
		arg.Status,
		arg.IdempotencyKey,
	)
	var i CreatePaymentRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.Reference,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFailedPaymentsForRetry = `-- name: GetFailedPaymentsForRetry :many
SELECT idempotency_key, reference
FROM payments
WHERE status = 'failed'
  AND next_retry_at IS NOT NULL
  AND next_retry_at <= datetime('now')
  AND attempts < 5
LIMIT 50
`

type GetFailedPaymentsForRetryRow struct {
	IdempotencyKey sql.NullString
	Reference      string
}

func (q *Queries) GetFailedPaymentsForRetry(ctx context.Context) ([]GetFailedPaymentsForRetryRow, error) {
	rows, err := q.db.QueryContext(ctx, getFailedPaymentsForRetry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFailedPaymentsForRetryRow
	for rows.Next() {
		var i GetFailedPaymentsForRetryRow
		if err := rows.Scan(&i.IdempotencyKey, &i.Reference); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPaymentByIdempotency = `-- name: GetPaymentByIdempotency :one
SELECT
    amount,
    currency,
    idempotency_key,
    reference,
    status,
    attempts,
    next_retry_at,
    created_at
FROM payments
WHERE idempotency_key = ? LIMIT 1
`

type GetPaymentByIdempotencyRow struct {
	Amount         int64
	Currency       string
	IdempotencyKey sql.NullString
	Reference      string
	Status         string
	Attempts       int64
	NextRetryAt    sql.NullString
	CreatedAt      string
}

func (q *Queries) GetPaymentByIdempotency(ctx context.Context, idempotencyKey sql.NullString) (GetPaymentByIdempotencyRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByIdempotency, idempotencyKey)
	var i GetPaymentByIdempotencyRow
	err := row.Scan(
		&i.Amount,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByReference = `-- name: GetPaymentByReference :one
SELECT
    id,
    amount,
    currency,
    idempotency_key,
    reference,
    status,
    attempts,
    next_retry_at,
    created_at
FROM payments
WHERE reference = ? LIMIT 1
`

type GetPaymentByReferenceRow struct {
	ID             int64
	Amount         int64
	Currency       string
	IdempotencyKey sql.NullString
	Reference      string
	Status         string
	Attempts       int64
	NextRetryAt    sql.NullString
	CreatedAt      string
}

func (q *Queries) GetPaymentByReference(ctx context.Context, reference string) (GetPaymentByReferenceRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByReference, reference)
	var i GetPaymentByReferenceRow
	err := row.Scan(
		&i.ID,
		&i.Amount,
		&i.Currency,
		&i.IdempotencyKey,
		&i.Reference,
		&i.Status,
		&i.Attempts,
		&i.NextRetryAt,
		&i.CreatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :exec
UPDATE payments
SET status = ?,
attempts = ?,
next_retry_at = ?
WHERE idempotency_key = ?
`

type UpdatePaymentStatusParams struct {
	Status         string
	Attempts       int64
	NextRetryAt    sql.NullString
	IdempotencyKey sql.NullString
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePaymentStatus,
		arg.Status,
		arg.Attempts,
		arg.NextRetryAt,
		arg.IdempotencyKey,
	)
	return err
}
